server:
  port: 6901

spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0KB
      max-file-size: 128MB
      max-request-size: 1024MB
  datasource:
    url: jdbc:h2:mem:pandb
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
    platform: h2
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

pan:
  base-dir: /Volumes/RiverFiles/Files/Idea/ideaWork/pan-base-dir
  quartz-jobs:
    clear-recycle-cron-schedule: 0/5 * * * * ?

